spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    url: jdbc:h2:mem:hodolog
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/baidb?useUnicode=yes&characterEncodeing=UTF-8
    username: root
    password: 1234
    
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

  sql:
    init:
      mode: always

  session:
    timeout: 86400

server:
  servlet:
    session:
      cookie:
        max-age: 172800

app:
  jwt-header: Authorization
  jwt-key: tJSp9fnML57SZhNk4RSew0JF03Op0e18F1gMq4JDOsxaM5UEU5o4ZVCRmPl0f7jPjNwdSKHae99SZB0jgH3SJw==
  jwt-expire: 43200